port: 3000
defaultTask:
  name: "Google Search (default)"
  plugin: OnlineSearch
  url: "https://www.google.com/search?q=%s"
tasks:
  "?":
    name: TaskSearch
    plugin: TaskSearch
  "=":
    name: Calculator
    plugin: Calculator
  m:
    name: "Mortgage Calculator"
    plugin: MortgageCalc
  # a:
  #   name: "Launch Mac Apps"
  #   keyTimeoutInMs: 500
  #   plugin: MacAppSearch
  #   paths:
  #     - "/Applications/"
  #     - "/Users/<user>/Applications/"
  #     - "/System/Library/PreferencePanes"
  e:
    name: "Launch Executables"
    plugin: UnixExecutableSearch
    keyTimeoutInMs: 500
    paths:
      - "/bin/"
      - "/usr/bin/"
      - "/usr/local/bin/"
  # f:
  #   name: "Search for Files"
  #   plugin: MacFileSearch
  #   keyTimeoutInMs: 500
  #   paths:
  #     - "/Users/<user>/Documents/"
  #     - "/Users/<user>/Downloads/"
  # k:
  #   name: KeePass1
  #   plugin: KeePass1
  #   databaseFilePath: "<database file location>"
  d:
    name: Dictionary
    plugin: OnlineSearch
    url: "https://www.merriam-webster.com/dictionary/%s"
  g:
    name: "Google Search"
    plugin: OnlineSearch
    url: "https://www.google.com/search?q=%s"
  h:
    name: "Haskell Search"
    plugin: OnlineSearch
    url: "https://www.google.com/search?q=haskell+%s"
  ho:
    name: Home
    plugin: OnlineSearch
    url: "http://unfettered-mind.net"
  pu:
    name: "Pursuit Search"
    plugin: OnlineSearch
    url: "https://pursuit.purescript.org/search?q=%s"
  py:
    name: "Python Search"
    plugin: OnlineSearch
    url: "https://www.google.com/search?q=python+%s"
  u:
    name: "USPS Tracking"
    plugin: OnlineSearch
    url: "https://tools.usps.com/go/TrackConfirmAction?tLabels=%s"
  w:
    name: "Wikipedia Search"
    plugin: OnlineSearch
    url: "https://wikipedia.org/wiki/Special:Search/%s"
  y:
    name: "YouTube Search"
    plugin: OnlineSearch
    url: "https://www.youtube.com/results?search_query=%s"
  z:
    name: "Amazon Search"
    plugin: OnlineSearch
    url: "https://www.amazon.com/s?field-keywords=%s"
  s:
    name: Snippets
    plugin: Snippets
    snippets:
      awk: "awk -F '|' '{ print $1\"|\"$2 }'"
      "mass rename": "for f in SOME-DIR/*SOME-FILE-2016-07*gz; do new=`echo $f | sed 's/SOME-DIR.[0-9_]*\\(SOME-FILE.*\\)/\\1/'`; echo mv $f $new; done | less"
      "Perl confess": "use Carp qw/ confess /; local $SIG{__DIE__} = sub { confess() };"
      "Perl dumper": "use Data::Dumper; print \"*****\\n\"; die Dumper($x);"
      pg_dump: "pg_dump -d DB -h HOST -p 5432 -U USER -Fc -t SOME_TABLE -f SOME-FILE"
      pg_restore: "pg_restore -d DB -h HOST -p 5432 -U USER -Fc -a -t SOME_TABLE SOME-FILE"
      "Postgres activities": "select * from public.pg_stat_activity;"
      "Postgres information_schema.columns": "select table_name, column_name, data_type from information_schema.columns where column_name ~* '';"
      "Postgres locks": "select * from pg_locks;"
      "Postgres table size": "select pg_size_pretty(pg_total_relation_size('SOME_TABLE')) as total, pg_size_pretty(pg_table_size('SOME_TABLE')) as table;"
      "python HTTP server": "python -m SimpleHTTPServer 9090"
      "tmux move window to the left": "swap-window -t -1"
      "tmux move window to the right": "swap-window -t +1"
      "wget directory": "wget -r -k -np -nH --cut-dirs=3 http://HOST/~USER/some-dir/"
      "zsh for loop": "for n in {1..5}; do echo $n; done"
